// data.js
export const articles = [
    {
      id: 1,
      title: "My First Blog Post",
      description: "This is my first blog post. I'm excited to share my thoughts with you!",
      date: "March 1, 2023",
      faculty: "Computer Science",
      imageUrl: "https://picsum.photos/id/1/600/400",
      author: "John Doe",
      authorAvatar: "https://picsum.photos/id/1/64",
    },
    {
        id: 2,
        title: "Introduction to Machine Learning",
        description: "In this post, we delve into the basics of machine learning and its applications.",
        date: "April 15, 2023",
        faculty: "Data Science",
        imageUrl: "https://picsum.photos/id/2/600/400",
        author: "Jane Smith",
        authorAvatar: "https://picsum.photos/id/2/64",
      },
      {
        id: 3,
        title: "The Future of Artificial Intelligence",
        description: "Exploring the potential impact of AI on various industries and society as a whole.",
        date: "May 5, 2023",
        faculty: "Artificial Intelligence",
        imageUrl: "https://picsum.photos/id/3/600/400",
        author: "Alex Johnson",
        authorAvatar: "https://picsum.photos/id/3/64",
      },
      {
        id: 4,
        title: "Web Development Trends in 2023",
        description: "A comprehensive overview of the latest trends in web development for the current year.",
        date: "June 20, 2023",
        faculty: "Web Development",
        imageUrl: "https://picsum.photos/id/4/600/400",
        author: "Emily Brown",
        authorAvatar: "https://picsum.photos/id/4/64",
      },
      {
        id: 5,
        title: "Cybersecurity Best Practices",
        description: "Learn about essential cybersecurity practices to keep your data safe online.",
        date: "July 10, 2023",
        faculty: "Cybersecurity",
        imageUrl: "https://picsum.photos/id/5/600/400",
        author: "Michael Clark",
        authorAvatar: "https://picsum.photos/id/5/64",
      },
      {
        id: 6,
        title: "Exploring Quantum Computing",
        description: "A beginner's guide to understanding the principles behind quantum computing.",
        date: "August 8, 2023",
        faculty: "Quantum Computing",
        imageUrl: "https://picsum.photos/id/6/600/400",
        author: "Sophia Lee",
        authorAvatar: "https://picsum.photos/id/6/64",
      },
      {
        id: 7,
        title: "Mobile App Development Strategies",
        description: "Strategies and tips for developing successful mobile applications in today's market.",
        date: "September 25, 2023",
        faculty: "Mobile Development",
        imageUrl: "https://picsum.photos/id/7/600/400",
        author: "William Rodriguez",
        authorAvatar: "https://picsum.photos/id/7/64",
      },
      {
        id: 8,
        title: "The Impact of Big Data Analytics",
        description: "Examining how big data analytics is revolutionizing various industries and business processes.",
        date: "October 12, 2023",
        faculty: "Data Analytics",
        imageUrl: "https://picsum.photos/id/8/600/400",
        author: "Olivia Martinez",
        authorAvatar: "https://picsum.photos/id/8/64",
      },
      {
        id: 9,
        title: "Ethical Considerations in Technology",
        description: "Discussing the ethical dilemmas arising from technological advancements and their implications.",
        date: "November 5, 2023",
        faculty: "Ethics in Technology",
        imageUrl: "https://picsum.photos/id/9/600/400",
        author: "Daniel Wilson",
        authorAvatar: "https://picsum.photos/id/9/64",
      },
      {
        id: 10,
        title: "User Interface Design Principles",
        description: "Key principles and guidelines for designing effective and user-friendly interfaces.",
        date: "December 20, 2023",
        faculty: "UI/UX Design",
        imageUrl: "https://picsum.photos/id/10/600/400",
        author: "Emma Taylor",
        authorAvatar: "https://picsum.photos/id/10/64",
      },
      {
        id: 11,
        title: "Cloud Computing Solutions",
        description: "Exploring the benefits and challenges of cloud computing solutions for businesses.",
        date: "January 8, 2024",
        faculty: "Cloud Computing",
        imageUrl: "https://picsum.photos/id/11/600/400",
        author: "Matthew Anderson",
        authorAvatar: "https://picsum.photos/id/11/64",
      },
      {
        id: 12,
        title: "Blockchain Technology Explained",
        description: "An overview of blockchain technology and its potential applications beyond cryptocurrencies.",
        date: "February 14, 2024",
        faculty: "Blockchain",
        imageUrl: "https://picsum.photos/id/12/600/400",
        author: "Ava Garcia",
        authorAvatar: "https://picsum.photos/id/12/64",
      },
      {
        id: 13,
        title: "The Rise of Augmented Reality",
        description: "Examining the increasing adoption of augmented reality technology across industries.",
        date: "March 5, 2024",
        faculty: "Augmented Reality",
        imageUrl: "https://picsum.photos/id/13/600/400",
        author: "Liam Baker",
        authorAvatar: "https://picsum.photos/id/13/64",
      },
      {
        id: 14,
        title: "Advances in Robotics",
        description: "Recent advancements in robotics and their implications for various sectors.",
        date: "April 18, 2024",
        faculty: "Robotics",
        imageUrl: "https://picsum.photos/id/14/600/400",
        author: "Ethan Green",
        authorAvatar: "https://picsum.photos/id/14/64",
      },
      {
        id: 15,
        title: "The Internet of Things (IoT) Revolution",
        description: "Exploring the transformative potential of IoT technologies in the digital age.",
        date: "May 10, 2024",
        faculty: "Internet of Things",
        imageUrl: "https://picsum.photos/id/15/600/400",
        author: "Isabella White",
        authorAvatar: "https://picsum.photos/id/15/64",
      },
  ];